# Generated by Django 4.0.5 on 2022-07-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.FloatField()),
                ('item_quantity', models.FloatField(blank=True, null=True)),
                ('item_des', models.CharField(max_length=255)),
                ('item_image', models.FileField(default='default.jpg', upload_to='static/images/items')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
