# Generated by Django 4.0.5 on 2022-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_accessories_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='games',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
